# Generated by Django 4.2.11 on 2024-04-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='sendemail',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='sendemail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sendemail',
            name='price',
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='email',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='GroupEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emaillist')),
            ],
        ),
    ]
