# Generated by Django 4.2.11 on 2024-04-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emaillist_remove_sendemail_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultEmailDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
