# Generated by Django 4.2.11 on 2024-04-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_defaultemaildetails_templateemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultemaildetails',
            name='sender_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
