# Generated by Django 4.2.11 on 2024-04-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_defaultemaildetails_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateemail',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
