# Generated by Django 4.2.11 on 2024-04-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_templateemail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateemail',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
