# Generated by Django 4.2.11 on 2024-04-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupemails',
            name='email',
        ),
        migrations.AddField(
            model_name='emaillist',
            name='group_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.groupemails'),
            preserve_default=False,
        ),
    ]
