# Generated by Django 4.2.11 on 2024-04-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='emails',
            field=models.CharField(max_length=255),
        ),
    ]
