# Generated by Django 4.2.11 on 2024-04-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_emails_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='emails',
            field=models.EmailField(max_length=254),
        ),
    ]
